// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQCkPDZB7c-VkB1ByfcnO9i0PtpAZqBaE',
    appId: '1:784983898683:android:1e413f4f5b267b135c7a1e',
    messagingSenderId: '784983898683',
    projectId: 'alu-startup-connect-e9b69',
    storageBucket: 'alu-startup-connect-e9b69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKDuAN-CWVbauZ7_xTe4Z7vOx5w4ZUM8Y',
    appId: '1:784983898683:ios:9fcac82619aa8a175c7a1e',
    messagingSenderId: '784983898683',
    projectId: 'alu-startup-connect-e9b69',
    storageBucket: 'alu-startup-connect-e9b69.firebasestorage.app',
    iosClientId: '784983898683-g7r0funhts443392cm2t2m6fuuskjf07.apps.googleusercontent.com',
    iosBundleId: 'com.alu.aluStartupConnect',
  );
}
